modLoader = "javafml"
loaderVersion = "${forge_loader_version}"
license = "${mod_license}"

[[mods]]
modId = "example_mod"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_desc}
'''
logoFile = "icon.png"

[[dependencies.example_mod]]
modId = "forge"
mandatory = true
versionRange = "${forge_loader_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"