site_name: FramingLib Developer Documentation

site_url: https://plaguetr.github.io/FramingLib/
copyright: 2026 Plague

repo_url: https://github.com/PlagueTR/FramingLib/
edit_uri: blob/main/FramingLibDocs/Docs/docs

remote_name: origin
remote_branch: gh-pages

nav:
  - Home: 'index.md'
  - Setting-up FramingLib: 'SettingUp/setting_up_framinglib.md'
  - Using FramingLib:
    - Creating a Layout Config Screen: 'Using/creating_a_layout_config_screen.md'
    - Creating a Layout Element: 'Using/creating_a_layout_element.md'
    - Saving the Config: 'Using/saving_the_config.md'
  - Integration:
    - ModMenu Integration: 'Integration/modmenu_integration.md'
    - Forge/NeoForge Integration: 'Integration/forge_integration.md'
  - API Reference:
    - Config:
      - LayoutConfigScreen: 'APIReference/layout_config_screen.md'
      - LayoutConfigScreenBuilder: 'APIReference/layout_config_screen_builder.md'
      - LayoutElement: 'APIReference/layout_element.md'
      - LayoutElementBuilder: 'APIReference/layout_element_builder.md'
    - Positioning:
      - Alignments: 'APIReference/alignments.md'
      - AlignmentSizeOffset: 'APIReference/alignment_size_offset.md'
    - Rendering:
      - Color: 'APIReference/color.md'
      - TextureInfo: 'APIReference/texture_info.md'
      - TextureUV: 'APIReference/texture_uv.md'

not_in_nav: |
  /stylesheets
  /javascripts

draft_docs: |
  drafts/

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/icon.png
  custom_dir: overrides
  locale: en
  features:
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mike:
      version_selector: true